--[[
    The asset registry's resolution policy.

    One rule, and everything here exists to hold it: **a lookup that misses falls
    back rather than erroring.** The engine runs with zero media today and must
    keep doing so once import exists, which means every failure path — no file, a
    loader that returns nil, a loader that throws, a kind nobody registered, even
    a placeholder producer that is itself broken — has to end with a record and a
    reason instead of a stack trace.

    The second thing asserted here is the distinction between `generated` and
    `fallback`. An asset declared with no path is procedural by design and is fine.
    An asset declared with a path that did not load is missing and is a bug. Fold
    those two into one state and the missing-asset report becomes a list nobody
    reads, which defeats the point of having one.

    Loaders are injected, so all of this runs under plain LuaJIT with no LÖVE.
]]

return function(t)
    local Registry = require('meatray.asset.registry')

    -- A loader that resolves from an in-memory filesystem, so the policy is
    -- tested rather than the disk.
    local FILES = {
        ['assets/sprites/imp.png'] = 'IMP-PIXELS',
        ['assets/sounds/shot.wav'] = 'SHOT-SAMPLES',
    }

    local function reset()
        Registry.clearAll()
        Registry.setLoader('sprite', function(record)
            local data = FILES[record.path]
            if not data then return nil, 'file not found: ' .. tostring(record.path) end
            return { data = data, settings = record.settings }
        end)
        Registry.setFallback('sprite', function(record)
            return { placeholder = true, name = record.name }
        end)
    end

    ---------------------------------------------------------------------
    t.describe('declaring')
    reset()

    local record = Registry.declare('imp', 'sprite',
        { path = 'assets/sprites/imp.png', settings = { angles = 8, frames = 4 } })

    t.eq(record.name, 'imp', 'the record keeps its logical name')
    t.eq(record.kind, 'sprite', 'and its kind')
    t.eq(record.path, 'assets/sprites/imp.png', 'and its source path')
    t.eq(record.settings.angles, 8, 'and the import settings, verbatim')
    t.eq(record.settings.frames, 4, 'both of them')
    t.eq(record.state, 'pending', 'and starts unresolved')
    t.eq(record.value, nil, 'with nothing loaded yet')

    t.eq(Registry.get('imp', 'sprite'), record, 'and can be looked up by name and kind')
    t.eq(Registry.get('nobody', 'sprite'), nil, 'an unknown name is nil, not an error')

    ---------------------------------------------------------------------
    t.describe('a source that loads')
    reset()
    Registry.declare('imp', 'sprite', { path = 'assets/sprites/imp.png' })

    local resolved = Registry.resolve('imp', 'sprite')
    t.eq(resolved.state, 'file', 'a present file resolves to the file state')
    t.eq(resolved.value.data, 'IMP-PIXELS', 'and the loader value comes back')
    t.eq(resolved.problem, nil, 'with no problem recorded')
    t.eq(#Registry.missing(), 0, 'and it does not count as missing')

    t.describe('resolution is cached')
    t.eq(resolved.attempts, 1, 'the loader ran once')
    Registry.resolve('imp', 'sprite')
    Registry.resolve('imp', 'sprite')
    t.eq(Registry.get('imp', 'sprite').attempts, 1, 'and is not re-run on every lookup')

    Registry.resolve('imp', 'sprite', true)
    t.eq(Registry.get('imp', 'sprite').attempts, 2,
         'but a forced resolve reloads, which is what re-import needs')

    ---------------------------------------------------------------------
    t.describe('no path at all is generated, not missing')
    reset()
    Registry.declare('crystal', 'sprite', { settings = { angles = 1, frames = 2 } })

    local gen = Registry.resolve('crystal', 'sprite')
    t.eq(gen.state, 'generated', 'a sprite with no source is generated by design')
    t.ok(gen.value ~= nil and gen.value.placeholder, 'and gets the procedural stand-in')
    t.eq(gen.problem, nil, 'with nothing to complain about')
    t.eq(#Registry.missing(), 0, 'and it is NOT reported as missing')

    local blank = Registry.declare('blank', 'sprite', { path = '' })
    t.eq(Registry.resolve('blank', 'sprite').state, 'generated',
         'an empty path counts as no path, not as a file that vanished')
    t.eq(blank.path, '', 'and the record still remembers what it was given')

    ---------------------------------------------------------------------
    t.describe('a source that is not there is missing, and still usable')
    reset()
    Registry.declare('ghost', 'sprite', { path = 'assets/sprites/ghost.png' })

    local ghost = Registry.resolve('ghost', 'sprite')
    t.eq(ghost.state, 'fallback', 'a named file that will not load is a fallback')
    t.ok(ghost.value ~= nil and ghost.value.placeholder,
         'and still resolves to something drawable')
    t.ok(ghost.problem ~= nil, 'with a stated reason')
    t.ok(ghost.problem:find('ghost.png') ~= nil,
         'that names the file', ghost.problem)

    local missing = Registry.missing()
    t.eq(#missing, 1, 'and it shows up in the missing list')
    t.eq(missing[1].name, 'ghost', 'by name')

    ---------------------------------------------------------------------
    t.describe('a loader that throws is a fallback, not a crash')
    reset()
    Registry.setLoader('sprite', function() error('corrupt PNG chunk', 0) end)
    Registry.declare('broken', 'sprite', { path = 'assets/sprites/broken.png' })

    local ok, result = pcall(Registry.resolve, 'broken', 'sprite')
    t.ok(ok, 'resolving does not propagate the error')
    t.eq(result.state, 'fallback', 'the record falls back instead')
    t.ok(result.problem:find('corrupt PNG chunk') ~= nil,
         'and keeps the loader message', result.problem)
    t.ok(result.value ~= nil, 'with a placeholder value')

    ---------------------------------------------------------------------
    t.describe('a kind with no loader')
    reset()
    Registry.declare('music', 'sound', { path = 'assets/sounds/theme.wav' })

    local music = Registry.resolve('music', 'sound')
    t.eq(music.state, 'fallback', 'an unregistered kind falls back')
    t.ok(music.problem:find('no loader') ~= nil, 'and says so plainly', music.problem)
    t.eq(music.value, nil, 'with no value, since no placeholder was registered either')
    t.eq(Registry.value('music', 'sound'), nil, 'and value() returns nil rather than erroring')

    ---------------------------------------------------------------------
    t.describe('even a broken placeholder does not raise')
    reset()
    Registry.setFallback('sprite', function() error('the placeholder generator is broken', 0) end)
    Registry.declare('doubly', 'sprite', { path = 'assets/sprites/nope.png' })

    local safe, doubly = pcall(Registry.resolve, 'doubly', 'sprite')
    t.ok(safe, 'a failing fallback is still not an error at the call site')
    t.eq(doubly.value, nil, 'the value is nil')
    t.ok(doubly.problem:find('placeholder failed') ~= nil,
         'and the message distinguishes the two failures', doubly.problem)

    ---------------------------------------------------------------------
    t.describe('value() is the call gameplay makes')
    reset()
    Registry.declare('imp', 'sprite', { path = 'assets/sprites/imp.png' })
    t.eq(Registry.value('imp', 'sprite').data, 'IMP-PIXELS', 'a hit returns the value')
    t.eq(Registry.value('never-declared', 'sprite'), nil, 'a miss returns nil, never an error')

    ---------------------------------------------------------------------
    t.describe('re-declaring replaces')
    reset()
    Registry.declare('imp', 'sprite', { path = 'assets/sprites/imp.png' })
    Registry.resolve('imp', 'sprite')
    Registry.declare('imp', 'sprite', { path = 'assets/sprites/gone.png' })

    local redeclared = Registry.get('imp', 'sprite')
    t.eq(redeclared.state, 'pending', 're-declaring drops the resolved state')
    t.eq(redeclared.value, nil, 'and the loaded value with it')
    t.eq(Registry.resolve('imp', 'sprite').state, 'fallback', 'so the new path is what gets tried')

    t.describe('forgetting')
    reset()
    Registry.declare('imp', 'sprite', { path = 'assets/sprites/imp.png' })
    Registry.forget('imp', 'sprite')
    t.eq(Registry.get('imp', 'sprite'), nil, 'a forgotten asset is gone')
    t.eq(Registry.count(), 0, 'and no longer counted')

    ---------------------------------------------------------------------
    -- The first collision any real game hits. A flat namespace resolves it by
    -- overwriting whichever was declared first, so the sprite becomes a sound and
    -- draws nothing, with no error to find.
    t.describe('names are namespaced per kind')
    reset()
    Registry.setLoader('sound', function(record)
        local data = FILES[record.path]
        if not data then return nil, 'file not found: ' .. tostring(record.path) end
        return { data = data }
    end)

    Registry.declare('door', 'sprite', { path = 'assets/sprites/imp.png' })
    Registry.declare('door', 'sound', { path = 'assets/sounds/shot.wav' })

    t.eq(Registry.count(), 2, 'a sprite and a sound may share a name')
    t.eq(Registry.get('door', 'sprite').kind, 'sprite', 'and each is found by its own kind')
    t.eq(Registry.get('door', 'sound').kind, 'sound', 'without one replacing the other')
    t.eq(Registry.value('door', 'sprite').data, 'IMP-PIXELS', 'resolving the sprite gets pixels')
    t.eq(Registry.value('door', 'sound').data, 'SHOT-SAMPLES', 'and the sound gets samples')

    t.eq(#Registry.find('door'), 2, 'find() reports both, for a browser asking what is taken')
    t.eq(Registry.find('door')[1].kind, 'sound', 'sorted by kind')
    t.eq(#Registry.find('nothing'), 0, 'and an unused name reports none')

    Registry.forget('door', 'sound')
    t.eq(Registry.get('door', 'sound'), nil, 'forgetting one kind drops only that one')
    t.ok(Registry.get('door', 'sprite') ~= nil, 'and leaves the other in place')

    -- A lookup with no kind is a caller bug, not a guess. Guessing would be right
    -- most of the time, which is the worst possible failure rate.
    t.describe('a lookup with no kind is refused')
    t.ok(not pcall(Registry.get, 'door'), 'get() without a kind raises rather than guessing')
    t.ok(not pcall(Registry.resolve, 'door'), 'and so does resolve()')
    t.ok(not pcall(Registry.value, 'door'), 'and value()')

    ---------------------------------------------------------------------
    t.describe('listing is sorted and filterable')
    reset()
    Registry.declare('zeta', 'sprite', {})
    Registry.declare('alpha', 'sprite', {})
    Registry.declare('shot', 'sound', {})

    local all = Registry.list()
    t.eq(#all, 3, 'every declared asset is listed')
    t.eq(all[1], 'shot', 'sorted by kind then name, so a listing does not reshuffle')
    t.eq(all[2], 'alpha', 'the sounds come before the sprites')
    t.eq(all[3], 'zeta', 'and each kind is sorted within itself')

    local sprites = Registry.list('sprite')
    t.eq(#sprites, 2, 'filtering by kind narrows the list')
    t.eq(sprites[1], 'alpha', 'and keeps the order')
    t.eq(Registry.count('sound'), 1, 'count agrees with list')

    local recs = Registry.records('sprite')
    t.eq(#recs, 2, 'records() returns the records themselves')
    t.eq(recs[1].name, 'alpha', 'in the same order')

    ---------------------------------------------------------------------
    t.describe('the inventory report')
    reset()
    Registry.declare('imp', 'sprite', { path = 'assets/sprites/imp.png' })   -- loads
    Registry.declare('ghost', 'sprite', { path = 'assets/sprites/ghost.png' }) -- missing
    Registry.declare('crystal', 'sprite', {})                                -- generated
    Registry.declare('player', 'sprite', {})                                 -- generated

    local report = Registry.report()
    t.eq(report.total, 4, 'every asset is counted')
    t.eq(report.file, 1, 'one came from a file')
    t.eq(report.generated, 2, 'two are procedural by design')
    t.eq(report.fallback, 1, 'and one fell back')
    t.eq(report.missing, 1, 'which is the number that matters')
    t.eq(report.pending, 0, 'reporting resolves everything first, so nothing is left pending')
    t.eq(report.byKind.sprite.total, 4, 'and the same is broken down per kind')
    t.eq(report.byKind.sprite.fallback, 1, 'including what is missing in each')

    -- The report must resolve what nobody has drawn yet. An asset whose absence
    -- is only discovered on the frame that needs it is an asset discovered in
    -- front of a player.
    t.describe('missing() resolves pending records first')
    reset()
    Registry.declare('never-touched', 'sprite', { path = 'assets/sprites/absent.png' })
    t.eq(Registry.get('never-touched', 'sprite').state, 'pending', 'nothing has been loaded')
    t.eq(#Registry.missing(), 1, 'and it is still reported as missing')

    t.describe('one line per missing asset, ready for a console')
    local lines = Registry.missingLines()
    t.eq(#lines, 1, 'one line')
    t.ok(lines[1]:find('never%-touched') ~= nil, 'naming the asset', lines[1])
    t.ok(lines[1]:find('absent.png') ~= nil, 'and the file it wanted')
    t.ok(lines[1]:find('sprite') ~= nil, 'and its kind')

    ---------------------------------------------------------------------
    t.describe('clear() keeps the wiring, clearAll() does not')
    reset()
    Registry.declare('imp', 'sprite', { path = 'assets/sprites/imp.png' })
    Registry.clear()
    t.eq(Registry.count(), 0, 'clear drops the records')
    t.ok(Registry.hasLoader('sprite'), 'but keeps the loaders, which are wiring rather than content')

    Registry.clearAll()
    t.ok(not Registry.hasLoader('sprite'), 'clearAll drops those too')

    ---------------------------------------------------------------------
    -- The facade has to be requirable with no LÖVE, or a dedicated server cannot
    -- load a game that mentions its own assets.
    t.describe('the asset facade loads headless')

    local savedLove = rawget(_G, 'love')
    rawset(_G, 'love', nil)

    for _, name in ipairs({ 'meatray.asset', 'meatray.asset.slice',
                            'meatray.asset.names', 'meatray.asset.registry',
                            'meatray.asset.spatial' }) do
        package.loaded[name] = nil
        local loaded, err = pcall(require, name)
        t.ok(loaded, ('%s loads with no love global'):format(name), err)
    end

    -- Scanning with no filesystem must be an empty list, not a crash: the browser
    -- calls it before it knows whether the project has an assets folder.
    local Asset = require('meatray.asset')
    t.eq(#Asset.scan('assets'), 0, 'scanning with no filesystem returns nothing, quietly')

    rawset(_G, 'love', savedLove)

    -- And the four headless modules must stay that way. Comments are stripped
    -- first, because each file's doc block states the rule and therefore names
    -- the APIs it forbids.
    t.describe('the headless asset modules never reference love')
    for _, path in ipairs({ 'meatray/asset/slice.lua', 'meatray/asset/names.lua',
                            'meatray/asset/registry.lua', 'meatray/asset/spatial.lua' }) do
        local handle = io.open(path, 'r')
        if not handle then
            t.ok(false, ('%s is readable'):format(path))
        else
            local src = handle:read('*a')
            handle:close()
            local code = src:gsub('%-%-%[%[.-%]%]', ''):gsub('%-%-[^\n]*', '')
            t.ok(not code:find('love%.'), ('%s is love-free'):format(path),
                 code:match('[^\n]*love%.[^\n]*'))
        end
    end

    Registry.clearAll()
end
