--[[
    meatray.sim.world — the tile grid and its doors.

    A world is a plain 2D array of tile codes plus per-tile door state. The
    engine works with any grid you hand it, whether generated by
    meatray.sim.worldgen or authored by hand, so nothing here depends on the
    generator.

    Tile codes:
        0            empty / walkable
        1..9         solid wall, the number selects a wall texture
        DOOR (10)    door, blocking while closed, walkable while open
        STAIRS_UP    (11) and STAIRS_DOWN (12): walkable markers
        RUBBLE (13)  what a destroyed wall leaves behind: walkable, and not
                     drawn as a wall -- the renderer casts straight through it,
                     so a destroyed wall reads as a hole. Debris on the floor is
                     a billboard the game spawns, not a tile.

    Wall HEIGHT is a side table, not a tile code: a solid tile is full height
    (1.0) unless setWallHeight says otherwise. Short walls (0 < h < 1) still
    block movement and still stop hitscan, but the renderer lets the ray
    continue past them so geometry behind shows over the top. That is the cheap
    half of variable height — one floor plane, no stacked levels. Stacked floors
    would collapse the per-column z-buffer; see docs/RESEARCH.md.

    Two things about a world change while it is running: doors open, and walls
    come down. They are tracked the same way -- a side table keyed by tile, a
    snapshot that lists only what differs from the map as authored, and an apply
    that takes such a list. Doing destruction as a second copy of the door
    mechanism rather than as a new mechanism is deliberate: the save system and
    the network layer already know how to carry one of these, so they carry two
    without learning anything.

    HEADLESS: this module must not touch love.graphics or any love drawing API.
]]

local World = {}

World.EMPTY       = 0
World.DOOR        = 10
World.STAIRS_UP   = 11
World.STAIRS_DOWN = 12
World.RUBBLE      = 13

local WorldMT = {}
WorldMT.__index = WorldMT

-- Wraps a tile grid. `grid` is indexed grid[y][x] with 1-based integer tiles,
-- matching the convention worldgen emits.
function World.new(grid, opts)
    opts = opts or {}
    assert(type(grid) == 'table' and type(grid[1]) == 'table', 'world needs a grid[y][x]')

    return setmetatable({
        grid = grid,
        height = #grid,
        width = #grid[1],
        doors = {},          -- ['x,y'] = { open = bool, openness = 0..1 }
        integrity = {},      -- ['x,y'] = hp remaining, only for damaged/destructible
        broken = {},         -- ['x,y'] = tile code it was before it came down
        -- Wall geometry side tables. Most walls are full height (base 0, height
        -- 1) and carry no entry. wallHeights is the short form: a single slab
        -- on the floor. wallSlabs is the general form: one or more slabs with
        -- arbitrary base heights (stacked / floating walls). See wallSlabsAt.
        wallHeights = opts.wallHeights or {},
        wallSlabs   = opts.wallSlabs or {},
        -- Walk surface height per tile, in wall units. Absent means 0 (the
        -- classic floor plane). Movers stand on this; the camera eye is
        -- floor + EYE_HEIGHT. Not the same as wall slabs: a raised floor is
        -- something you walk on, a slab is a vertical face.
        floorHeights = opts.floorHeights or {},
        -- Thin walls: segments at arbitrary angles, or nil. Created on demand
        -- by :addSegment rather than always, so a world that has none carries
        -- no table and the collision and render passes both short-circuit on a
        -- single nil test.
        segments = opts.segments,

        theme = opts.theme,  -- an opaque name the render layer may interpret
        spawn = opts.spawn,  -- { x = , y = } if the generator picked one

        -- Bumped whenever the grid itself changes shape. Anything holding
        -- derived geometry -- a lighting bake, a batched mesh, a navmesh --
        -- compares this against what it last built from and rebuilds when they
        -- differ. A counter rather than a callback list, because the renderer
        -- must be able to notice on its own schedule: a wall that comes down
        -- during a net apply would otherwise invalidate a cache mid-frame.
        revision = 0,
    }, WorldMT)
end

function WorldMT:inBounds(tx, ty)
    return tx >= 1 and ty >= 1 and tx <= self.width and ty <= self.height
end

-- Out of bounds reads as solid so rays and movement stop at the edge rather
-- than indexing nil.
function WorldMT:tileAt(tx, ty)
    if not self:inBounds(tx, ty) then return 1 end
    return self.grid[ty][tx] or World.EMPTY
end

local function doorKey(tx, ty)
    return tx .. ',' .. ty
end

function WorldMT:doorAt(tx, ty)
    return self.doors[doorKey(tx, ty)]
end

-- Registers a door on a tile. Doors are tracked separately from the grid so a
-- door's open state can change without rewriting the map.
function WorldMT:addDoor(tx, ty, open)
    self.grid[ty][tx] = World.DOOR
    self.doors[doorKey(tx, ty)] = { open = open or false, openness = open and 1 or 0 }
    return self
end

-- Notifies watchers that solidity at (tx, ty) may have changed. Gas fields and
-- anything else that caches "what can flow through here" subscribe once; the
-- world emits, so a caller that opens a door or knocks a wall down cannot forget
-- to wake them. `onShapeChange` is still honoured for one-off hooks.
function WorldMT:_emitShapeChange(tx, ty, kind)
    local list = self._shapeWatchers
    if list then
        for i = 1, #list do
            list[i](self, tx, ty, kind)
        end
    end
    if self.onShapeChange then
        self.onShapeChange(self, tx, ty, kind)
    end
end

-- Subscribe to door open/close, destruction and repair. Returns an unsubscribe
-- function. Order of delivery is registration order; a watcher that raises is
-- not caught — the shape change already happened, and hiding the error would
-- only make the gas (or whatever) silently wrong.
function WorldMT:watchShape(fn)
    if type(fn) ~= 'function' then
        error('world:watchShape needs a function', 2)
    end
    local list = self._shapeWatchers
    if not list then
        list = {}
        self._shapeWatchers = list
    end
    list[#list + 1] = fn
    return function()
        for i = #list, 1, -1 do
            if list[i] == fn then
                table.remove(list, i)
                return
            end
        end
    end
end

function WorldMT:setDoorOpen(tx, ty, open)
    local door = self:doorAt(tx, ty)
    if not door then return false end
    local want = open and true or false
    if door.open == want then return true end
    door.open = want
    self:_emitShapeChange(tx, ty, 'door')
    return true
end

function WorldMT:toggleDoor(tx, ty)
    local door = self:doorAt(tx, ty)
    if not door then return false end
    door.open = not door.open
    self:_emitShapeChange(tx, ty, 'door')
    return true
end

-- Blocks movement and rays. A door blocks only while shut.
function WorldMT:isSolid(tx, ty)
    local tile = self:tileAt(tx, ty)
    if tile == World.EMPTY then return false end
    if tile == World.STAIRS_UP or tile == World.STAIRS_DOWN then return false end
    if tile == World.RUBBLE then return false end
    if tile == World.DOOR then
        local door = self:doorAt(tx, ty)
        return not (door and door.open)
    end
    return true
end

-- True for tiles a walker may occupy, which is the same question as isSolid for
-- now but kept separate: games add hazards and one-way tiles here.
function WorldMT:isWalkable(tx, ty)
    return not self:isSolid(tx, ty)
end

-- Advances door animation. Openness is presentation state, but it lives here
-- because the renderer must not mutate world state and because a networked host
-- has to be able to send it.
function WorldMT:update(dt, speed)
    speed = speed or 4
    for _, door in pairs(self.doors) do
        local target = door.open and 1 or 0
        if door.openness ~= target then
            local step = speed * dt
            if door.openness < target then
                door.openness = math.min(target, door.openness + step)
            else
                door.openness = math.max(target, door.openness - step)
            end
        end
    end
end

---------------------------------------------------------------------------
-- Thin walls
--
-- A tile grid only makes walls at right angles on a lattice, which is why every
-- raycaster built on one looks like it was built on one. A segment is a line
-- between two arbitrary points, and it is opaque and full height -- see
-- meatray/sim/segments.lua for why those two limits are where the affordable
-- version stops.
---------------------------------------------------------------------------

function WorldMT:addSegment(x1, y1, x2, y2, tex, opts)
    if not self.segments then
        self.segments = require('meatray.sim.segments').new()
    end
    return self.segments:add(x1, y1, x2, y2, tex, opts)
end

function WorldMT:segmentCount()
    return self.segments and self.segments.count or 0
end

function WorldMT:clearSegments()
    if self.segments then self.segments:clear() end
    return self
end

---------------------------------------------------------------------------
-- Wall height and slabs (variable geometry on one floor plane)
--
-- A solid tile is a full wall (one slab base=0 height=1) until told otherwise.
-- Two ways to say otherwise:
--
--   setWallHeight(tx, ty, h)     one slab on the floor, height h in (0, 1]
--   addWallSlab(tx, ty, base, h) a slab at base z, height h; several per tile
--
-- Stacked / floating walls are just multiple slabs. The renderer records every
-- slab the ray hits and continues past any tile that does not cover the full
-- [0, 1] range, so a gap at eye height lets you see what is behind. Movement
-- and isSolid are unchanged — you still cannot walk through a half-height
-- pillar. Setting geometry on a non-solid tile is refused.
--
-- This is still one floor plane (camera at EYE_HEIGHT, no pitch). Multi-level
-- *floors* you can walk on are a different feature.
---------------------------------------------------------------------------

-- Camera eye height in wall units, matching the wall loop's assumption that a
-- full wall is centred on the horizon (eye at mid-height).
World.EYE_HEIGHT = 0.5

local DEFAULT_SLABS = { { base = 0, height = 1 } }

-- True when a floor-based wall of this height fully occludes the camera eye.
function World.occludesEye(height)
    height = height or 1
    return height >= World.EYE_HEIGHT
end

-- True when a slab [base, base+height) covers the eye height. `eye` defaults
-- to EYE_HEIGHT; pass the camera's absolute eyeZ when standing on a raised
-- floor so occlusion matches what the player can actually see over.
function World.slabOccludesEye(base, height, eye)
    base = base or 0
    height = height or 1
    local top = base + height
    eye = eye or World.EYE_HEIGHT
    return base <= eye and top > eye - 1e-9
end

-- True when the union of slabs covers [0, 1] with no gaps — a ray-stopping
-- face. Insertion-merge on a sorted list; n is small (one or two slabs).
function World.slabsBlockRay(slabs)
    if not slabs or #slabs == 0 then return true end
    local spans = {}
    for i = 1, #slabs do
        local s = slabs[i]
        local b, h = s.base or 0, s.height or 1
        if h > 0 then spans[#spans + 1] = { b, b + h } end
    end
    if #spans == 0 then return false end
    table.sort(spans, function(a, b) return a[1] < b[1] end)

    local coverLo, coverHi = spans[1][1], spans[1][2]
    for i = 2, #spans do
        if spans[i][1] <= coverHi + 1e-9 then
            if spans[i][2] > coverHi then coverHi = spans[i][2] end
        else
            break
        end
    end
    return coverLo <= 1e-9 and coverHi >= 1 - 1e-9
end

-- Returns the slab list for a tile. Never nil; default is one full wall.
-- The returned table must not be mutated by the caller — it may be shared.
function WorldMT:wallSlabsAt(tx, ty)
    if not self:inBounds(tx, ty) then return DEFAULT_SLABS end
    local key = doorKey(tx, ty)
    local slabs = self.wallSlabs[key]
    if slabs and #slabs > 0 then return slabs end
    local h = self.wallHeights[key]
    if h ~= nil then
        -- Ephemeral one-slab view for the short-height path. Not cached: the
        -- renderer must not hold it past the column.
        return { { base = 0, height = h } }
    end
    return DEFAULT_SLABS
end

-- Convenience: height of a single floor-based slab, or 1 for full/default, or
-- the top of the highest slab when geometry is stacked.
function WorldMT:wallHeightAt(tx, ty)
    if not self:inBounds(tx, ty) then return 1 end
    local key = doorKey(tx, ty)
    if self.wallHeights[key] ~= nil then return self.wallHeights[key] end
    local slabs = self.wallSlabs[key]
    if not slabs or #slabs == 0 then return 1 end
    if #slabs == 1 and (slabs[1].base or 0) <= 1e-9 then
        return slabs[1].height or 1
    end
    local top = 0
    for i = 1, #slabs do
        local s = slabs[i]
        local t = (s.base or 0) + (s.height or 0)
        if t > top then top = t end
    end
    return top
end

-- Sets a single floor-based short wall. Pass nil or 1 to clear to full height.
-- Clears any multi-slab list on the tile so the two representations cannot
-- disagree.
function WorldMT:setWallHeight(tx, ty, height)
    if not self:inBounds(tx, ty) then return false end
    if not self:isSolid(tx, ty) then return false end

    local key = doorKey(tx, ty)
    self.wallSlabs[key] = nil

    if height == nil or height >= 1 then
        self.wallHeights[key] = nil
        return true
    end

    if type(height) ~= 'number' or height ~= height then return false end
    if height <= 0 then return false end

    self.wallHeights[key] = height
    return true
end

-- Adds a slab at base z with the given height. Both in wall units; base may be
-- above the floor (a floating rail, an upper storey face). Replaces the simple
-- wallHeights entry if one was there. Returns false on bad input.
function WorldMT:addWallSlab(tx, ty, base, height)
    if not self:inBounds(tx, ty) then return false end
    if not self:isSolid(tx, ty) then return false end
    if type(base) ~= 'number' or base ~= base or base < 0 then return false end
    if type(height) ~= 'number' or height ~= height or height <= 0 then return false end

    local key = doorKey(tx, ty)
    self.wallHeights[key] = nil

    local list = self.wallSlabs[key]
    if not list then
        list = {}
        self.wallSlabs[key] = list
    end
    list[#list + 1] = { base = base, height = height }
    table.sort(list, function(a, b) return (a.base or 0) < (b.base or 0) end)
    return true
end

-- Replaces all slabs on a tile. Pass nil or {} to clear to full height.
function WorldMT:setWallSlabs(tx, ty, slabs)
    if not self:inBounds(tx, ty) then return false end
    if not self:isSolid(tx, ty) then return false end

    local key = doorKey(tx, ty)
    self.wallHeights[key] = nil

    if slabs == nil or (type(slabs) == 'table' and #slabs == 0) then
        self.wallSlabs[key] = nil
        return true
    end
    if type(slabs) ~= 'table' then return false end

    local list = {}
    for i = 1, #slabs do
        local s = slabs[i]
        local b, h = s.base or 0, s.height or 0
        if type(b) == 'number' and b == b and b >= 0
           and type(h) == 'number' and h == h and h > 0 then
            list[#list + 1] = { base = b, height = h }
        end
    end
    if #list == 0 then
        self.wallSlabs[key] = nil
        return true
    end
    -- One floor-based full wall is the default: store nothing.
    if #list == 1 and list[1].base <= 1e-9 and list[1].height >= 1 - 1e-9 then
        self.wallSlabs[key] = nil
        return true
    end
    -- One floor-based short wall: prefer the compact form.
    if #list == 1 and list[1].base <= 1e-9 and list[1].height < 1 then
        self.wallHeights[key] = list[1].height
        self.wallSlabs[key] = nil
        return true
    end
    table.sort(list, function(a, b) return a.base < b.base end)
    self.wallSlabs[key] = list
    return true
end

---------------------------------------------------------------------------
-- Floor height (walkable elevation)
--
-- The walk surface on a tile, in the same wall units wall slabs use. Default 0
-- is the classic floor. Raising a tile lets a mover stand higher; the camera
-- eye follows as floor + EYE_HEIGHT. Stairs are just adjacent tiles with
-- different floor heights and a step the mover is allowed to take
-- (Collide.MAX_STEP).
--
-- Destroying a wall does not change the floor under the rubble — the hole is
-- walkable at the same elevation unless something sets it explicitly.
---------------------------------------------------------------------------

function WorldMT:floorHeightAt(tx, ty)
    if not self:inBounds(tx, ty) then return 0 end
    return self.floorHeights[doorKey(tx, ty)] or 0
end

-- Sample under a world point (entity feet). The tile the point sits in.
function WorldMT:floorHeightAtPoint(x, y)
    local tx, ty = math.floor(x) + 1, math.floor(y) + 1
    return self:floorHeightAt(tx, ty)
end

-- Sets the walk surface height. Pass nil or 0 to clear back to the default plane.
-- Rebuilds floor risers so the platform edge is a visible (and solid) face,
-- unless opts.defer is true (batch apply, then call rebuildFloorRisers once).
function WorldMT:setFloorHeight(tx, ty, height, opts)
    if not self:inBounds(tx, ty) then return false end
    local key = doorKey(tx, ty)
    if height == nil or height == 0 then
        self.floorHeights[key] = nil
    else
        if type(height) ~= 'number' or height ~= height then return false end
        if height < 0 then return false end
        self.floorHeights[key] = height
    end
    -- Floor height is derived geometry for the renderer; bump revision so the
    -- floor-height texture and lighting bake know to refresh.
    self.revision = (self.revision or 0) + 1
    if not (opts and opts.defer) then
        self:rebuildFloorRisers()
    end
    return true
end

-- Unique floor heights present in the world, sorted ascending, always including
-- 0. Used by the multi-plane floor cast so each raised surface gets a pass.
function WorldMT:floorHeightPlanes()
    local seen, list = { [0] = true }, { 0 }
    for _, z in pairs(self.floorHeights) do
        if type(z) == 'number' and z > 0 and not seen[z] then
            seen[z] = true
            list[#list + 1] = z
        end
    end
    table.sort(list)
    return list
end

-- Vertical faces at floor-height discontinuities between open tiles. Without
-- these a raised platform has a walk surface (and a drawn top) but no sides —
-- you float above the base floor with nothing under the edge. Built as auto
-- segments so hand-authored thin walls are not wiped.
--
-- Geometry: for each open tile at height hi and each cardinal open neighbour
-- at height lo < hi, a segment along the shared edge from lo to hi.
function WorldMT:rebuildFloorRisers()
    if self.segments then
        self.segments:clearAuto()
    end

    local any = false
    for _ in pairs(self.floorHeights) do any = true; break end
    if not any then return self end

    local DX = { 1, -1, 0, 0 }
    local DY = { 0, 0, 1, -1 }
    -- Edge endpoints in world coords for the side of tile (tx,ty) facing (dx,dy).
    -- Tiles are [tx-1, tx] x [ty-1, ty] in world space.
    local function edge(tx, ty, dx, dy)
        if dx == 1 then
            return tx, ty - 1, tx, ty
        elseif dx == -1 then
            return tx - 1, ty - 1, tx - 1, ty
        elseif dy == 1 then
            return tx - 1, ty, tx, ty
        else
            return tx - 1, ty - 1, tx, ty - 1
        end
    end

    for key, hi in pairs(self.floorHeights) do
        local sx, sy = key:match('^(%-?%d+),(%-?%d+)$')
        local tx, ty = tonumber(sx), tonumber(sy)
        if tx and ty and hi and hi > 0 and not self:isSolid(tx, ty) then
            for k = 1, 4 do
                local nx, ny = tx + DX[k], ty + DY[k]
                if self:inBounds(nx, ny) and not self:isSolid(nx, ny) then
                    local lo = self:floorHeightAt(nx, ny)
                    if hi > lo + 1e-9 then
                        local x1, y1, x2, y2 = edge(tx, ty, DX[k], DY[k])
                        self:addSegment(x1, y1, x2, y2, {
                            tex = 1,
                            base = lo,
                            height = hi - lo,
                            auto = true,
                        })
                    end
                end
            end
        end
    end
    return self
end

---------------------------------------------------------------------------
-- Destruction
--
-- A wall is destructible only once something says so. That is the opposite of
-- the obvious design, where every wall has hit points and most of them are set
-- to infinity, and it is chosen because the common case in a level is a wall
-- that must never come down. Making indestructibility the default means a map
-- cannot accidentally become perforated by a stray explosion, and it keeps the
-- side table proportional to the number of breakable walls rather than to the
-- size of the map.
---------------------------------------------------------------------------

-- Marks a tile as breakable with `hp` hit points. Returns false for a tile that
-- is not currently solid, since there is nothing there to break.
function WorldMT:setDestructible(tx, ty, hp)
    if not self:inBounds(tx, ty) then return false end
    if not self:isSolid(tx, ty) then return false end
    self.integrity[doorKey(tx, ty)] = hp or 100
    return true
end

function WorldMT:integrityAt(tx, ty)
    return self.integrity[doorKey(tx, ty)]
end

function WorldMT:isDestructible(tx, ty)
    return self.integrity[doorKey(tx, ty)] ~= nil
end

-- Applies damage. Returns destroyed(bool), hpRemaining.
--
-- Damage to a tile that was never marked destructible does nothing and reports
-- nothing -- an explosion is allowed to splash across a whole room and ask every
-- tile in it, and the ones that cannot break are not an error.
function WorldMT:damageTile(tx, ty, amount)
    local key = doorKey(tx, ty)
    local hp = self.integrity[key]
    if hp == nil then return false, nil end

    hp = hp - (amount or 0)

    if hp > 0 then
        self.integrity[key] = hp
        return false, hp
    end

    self:destroyTile(tx, ty)
    return true, 0
end

-- Brings a tile down regardless of hit points. Remembers what it was, both so a
-- save can describe the change as a difference from the authored map and so a
-- game can repair it.
function WorldMT:destroyTile(tx, ty)
    if not self:inBounds(tx, ty) then return false end

    local key = doorKey(tx, ty)
    local was = self.grid[ty][tx]
    if was == World.RUBBLE then return false end

    self.broken[key] = was
    self.integrity[key] = nil
    self.wallHeights[key] = nil
    self.wallSlabs[key] = nil
    self.grid[ty][tx] = World.RUBBLE
    self.revision = self.revision + 1

    -- Told, not polled -- and unlike the revision counter this one is a single
    -- game-owned hook rather than a cache. Debris is a thing that happens once,
    -- at a known place, with the tile code that was there; reconstructing that
    -- by diffing the grid against last frame would be worse in every way.
    --
    -- It fires on the client too, during a world delta apply, which is what you
    -- want: debris is cosmetic, so every machine spawning its own from the same
    -- event costs no bandwidth and needs no replication.
    if self.onDestroy then self.onDestroy(self, tx, ty, was) end

    -- A destroyed door stops being a door. Leaving the entry behind would give
    -- the animation loop something to keep stepping and would let isSolid
    -- consult a door on a tile that is now a hole.
    self.doors[key] = nil

    -- Gas (and anything else that sleeps on "solidity did not change") has to
    -- learn the hole opened. Same emission as a door toggle.
    self:_emitShapeChange(tx, ty, 'destroy')

    return true
end

-- Puts a destroyed tile back. The inverse exists because destruction is state
-- like any other: a level that reloads, a round that restarts, or an undo in
-- the editor all need it, and reconstructing the original grid from the map
-- file is a much bigger hammer.
function WorldMT:repairTile(tx, ty, hp)
    local key = doorKey(tx, ty)
    local was = self.broken[key]
    if was == nil then return false end

    self.grid[ty][tx] = was
    self.broken[key] = nil
    self.revision = self.revision + 1

    if hp then self.integrity[key] = hp end
    self:_emitShapeChange(tx, ty, 'repair')
    return true
end

-- What changed relative to the map as authored. Mirrors :snapshot() for doors,
-- deliberately: same key format, same "only the differences" rule, so the net
-- and save layers carry it with the code they already have.
function WorldMT:tileSnapshot()
    local out = {}
    for key in pairs(self.broken) do out[key] = 1 end
    return out
end

function WorldMT:applyTileSnapshot(snap)
    if not snap then return self end

    for key, gone in pairs(snap) do
        local sx, sy = key:match('^(-?%d+),(-?%d+)$')
        local tx, ty = tonumber(sx), tonumber(sy)
        if tx and ty and self:inBounds(tx, ty) then
            if gone == 1 then
                if self.broken[key] == nil then self:destroyTile(tx, ty) end
            else
                self:repairTile(tx, ty)
            end
        end
    end

    return self
end

-- Door state is the only mutable part of a world, so it is all the network and
-- the save system need.
function WorldMT:snapshot()
    local out = {}
    for key, door in pairs(self.doors) do
        out[key] = door.open and 1 or 0
    end
    return out
end

function WorldMT:applySnapshot(snap)
    if not snap then return self end
    for key, open in pairs(snap) do
        local door = self.doors[key]
        if door then door.open = (open == 1) end
    end
    return self
end

return World
