--[[
    meatray.sim.world — the tile grid and its doors.

    A world is a plain 2D array of tile codes plus per-tile door state. The
    engine works with any grid you hand it, whether generated by
    meatray.sim.worldgen or authored by hand, so nothing here depends on the
    generator.

    Tile codes:
        0            empty / walkable
        1..9         solid wall, the number selects a wall texture
        DOOR (10)    door, blocking while closed, walkable while open
        STAIRS_UP    (11) and STAIRS_DOWN (12): walkable markers

    HEADLESS: this module must not touch love.graphics or any love drawing API.
]]

local World = {}

World.EMPTY       = 0
World.DOOR        = 10
World.STAIRS_UP   = 11
World.STAIRS_DOWN = 12

local WorldMT = {}
WorldMT.__index = WorldMT

-- Wraps a tile grid. `grid` is indexed grid[y][x] with 1-based integer tiles,
-- matching the convention worldgen emits.
function World.new(grid, opts)
    opts = opts or {}
    assert(type(grid) == 'table' and type(grid[1]) == 'table', 'world needs a grid[y][x]')

    return setmetatable({
        grid = grid,
        height = #grid,
        width = #grid[1],
        doors = {},          -- ['x,y'] = { open = bool, openness = 0..1 }
        theme = opts.theme,  -- an opaque name the render layer may interpret
        spawn = opts.spawn,  -- { x = , y = } if the generator picked one
    }, WorldMT)
end

function WorldMT:inBounds(tx, ty)
    return tx >= 1 and ty >= 1 and tx <= self.width and ty <= self.height
end

-- Out of bounds reads as solid so rays and movement stop at the edge rather
-- than indexing nil.
function WorldMT:tileAt(tx, ty)
    if not self:inBounds(tx, ty) then return 1 end
    return self.grid[ty][tx] or World.EMPTY
end

local function doorKey(tx, ty)
    return tx .. ',' .. ty
end

function WorldMT:doorAt(tx, ty)
    return self.doors[doorKey(tx, ty)]
end

-- Registers a door on a tile. Doors are tracked separately from the grid so a
-- door's open state can change without rewriting the map.
function WorldMT:addDoor(tx, ty, open)
    self.grid[ty][tx] = World.DOOR
    self.doors[doorKey(tx, ty)] = { open = open or false, openness = open and 1 or 0 }
    return self
end

function WorldMT:setDoorOpen(tx, ty, open)
    local door = self:doorAt(tx, ty)
    if not door then return false end
    door.open = open and true or false
    return true
end

function WorldMT:toggleDoor(tx, ty)
    local door = self:doorAt(tx, ty)
    if not door then return false end
    door.open = not door.open
    return true
end

-- Blocks movement and rays. A door blocks only while shut.
function WorldMT:isSolid(tx, ty)
    local tile = self:tileAt(tx, ty)
    if tile == World.EMPTY then return false end
    if tile == World.STAIRS_UP or tile == World.STAIRS_DOWN then return false end
    if tile == World.DOOR then
        local door = self:doorAt(tx, ty)
        return not (door and door.open)
    end
    return true
end

-- True for tiles a walker may occupy, which is the same question as isSolid for
-- now but kept separate: games add hazards and one-way tiles here.
function WorldMT:isWalkable(tx, ty)
    return not self:isSolid(tx, ty)
end

-- Advances door animation. Openness is presentation state, but it lives here
-- because the renderer must not mutate world state and because a networked host
-- has to be able to send it.
function WorldMT:update(dt, speed)
    speed = speed or 4
    for _, door in pairs(self.doors) do
        local target = door.open and 1 or 0
        if door.openness ~= target then
            local step = speed * dt
            if door.openness < target then
                door.openness = math.min(target, door.openness + step)
            else
                door.openness = math.max(target, door.openness - step)
            end
        end
    end
end

-- Door state is the only mutable part of a world, so it is all the network and
-- the save system need.
function WorldMT:snapshot()
    local out = {}
    for key, door in pairs(self.doors) do
        out[key] = door.open and 1 or 0
    end
    return out
end

function WorldMT:applySnapshot(snap)
    if not snap then return self end
    for key, open in pairs(snap) do
        local door = self.doors[key]
        if door then door.open = (open == 1) end
    end
    return self
end

return World
