-- Regenerate the wire/save compatibility corpus (G6).
--
--   luajit scripts/gen_corpus.lua
--
-- Writes tests/fixtures/compat_corpus.lua: a Lua table of every fixture's
-- name, kind, format version, and the bytes it encodes to, stored as hex so
-- the file survives git line-ending conversion. Run this ONLY when a format
-- version is deliberately bumped — never to make a failing compat test pass,
-- which would be deleting the evidence that the format changed. Run from the
-- repo root.

package.path = './?.lua;./?/init.lua;' .. package.path

local Fixtures = require('tests.support.corpus_fixtures')
Fixtures.pinBackend()

local function toHex(s)
    local parts = {}
    for i = 1, #s do parts[i] = ('%02x'):format(s:byte(i)) end
    return table.concat(parts)
end

local out = {
    '-- AUTO-GENERATED by scripts/gen_corpus.lua — do not hand-edit.',
    '-- The golden wire/save corpus (G6): bytes THIS build emits that every',
    '-- future build must still decode. Regenerate ONLY on a deliberate format',
    '-- version bump; never to silence a failing test.',
    'return {',
}

for _, fx in ipairs(Fixtures.all()) do
    local obj = fx.build()
    local bytes = fx.encode(obj)
    if type(bytes) ~= 'string' then
        io.stderr:write('FIXTURE ' .. fx.name .. ' did not encode to a string\n')
        os.exit(1)
    end
    out[#out + 1] = ('  { name = %q, kind = %q, version = %d, bytes = %q },')
        :format(fx.name, fx.kind, fx.version, toHex(bytes))
end

out[#out + 1] = '}'
out[#out + 1] = ''

local path = 'tests/fixtures/compat_corpus.lua'
os.execute('mkdir tests\\fixtures 2>nul')          -- Windows; harmless if it exists
local f = assert(io.open(path, 'wb'))
f:write(table.concat(out, '\n'))
f:close()

print('wrote ' .. path .. ' with ' .. #Fixtures.all() .. ' fixtures')
